aws lambda update-function-configuration --function-name teste_lambda \
    --environment "Variables={SCALE_PERIOD_MINS=1,SCALE_UP_THRESHOLD=0.30,SCALE_UP_EVALUATION_PERIOD=3,SCALE_UP_DATAPOINTS_REQUIRED=3,SCALE_DOWN_THRESHOLD=0.10,SCALE_DOWN_EVALUATION_PERIOD=5,SCALE_DOWN_DATAPOINTS_REQUIRED=3,SCALE_DOWN_MIN_ITER_AGE_MINS=30,DRY_RUN=false}" 
